export const randomPhrases = [
  "Silence is the best song",
  "Music paused, but not your heart",
  "Loading the next track...",
  "The stage is set, waiting for music",
  "Life is a song - this is just a rest",
  "DJ preparing the next banger",
  "Between notes lies the magic",
  "The universe is tuning its instruments",
  "Your next favorite song is coming",
  "Take a breath... the music will return",
  "The rhythm is in your imagination",
  "Even rockstars need coffee breaks",
  "This silence is just a musical interlude",
  "Good music takes time to load",
  "The beat drops in 3... 2... 1...",
  "Soundwaves dreaming of your speakers",
  "The playlist of life has a skip button",
  "Melodies are brewing...",
  "Your ears deserve this moment of silence",
  "Next track loading with extra bass",
  "The concert in your mind never ends",
  "Vinyl souls need silent moments too",
  "The music will rise like phoenix",
  "Symphony of silence before the storm",
  "Headphones at the ready...",
  "The algorithm is cooking your jam",
  "Air guitar solo incoming",
  "Music is loading with 200% emotion",
  "Your personal soundtrack is buffering",
  "The speakers are taking a power nap",
  "Silence: nature's most underrated track",
  "The bass is charging its energy",
  "Musical genius requires coffee first",
  "Your next earworm is being born",
  "The quiet before the drop",
  "Spotify elves are polishing your song",
  "Music is the answer - just loading Q",
  "The metronome of life is ticking",
  "Your patience is the best intro",
  "The universe's playlist is shuffling",
  "Neurons dancing to silent beats",
  "Music is coming - believe in the beat",
  "The encore is worth waiting for",
  "Sound engineer adjusting the cosmos",
  "Your vibe attracts your tribe (and songs)",
  "The silence between notes makes music",
  "Next song selected by cosmic DJs",
  "The headphones of destiny are charging",
  "Musical aurora loading in 4K",
  "Your soul's volume knob is at 11",
  "The concert never ends - just intermissions",
];

export function getRandomPhrase() {
  return randomPhrases[Math.floor(Math.random() * randomPhrases.length)];
}
